---
parser: babel-eslint
parserOptions:
  ecmaVersion: 2020
  sourceType: module
env:
  node: true
  jest/globals: true
extends:
  - airbnb-base
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:jest/recommended
  - plugin:prettier/recommended
rules:
  class-methods-use-this: "off"
  camelcase:
    - "error"
    - ignoreDestructuring: true
      properties: never
  no-continue: "off"
  no-bitwise: "off"
  no-underscore-dangle: "off"
  no-param-reassign:
    - "error"
    - props: false
  no-restricted-syntax:
    - "error"
    - ForInStatement
    - LabeledStatement
    - WithStatement
  no-shadow: "off"
  import/prefer-default-export: "off"
  import/extensions: "off"
  import/no-cycle: "off"
  no-unused-vars:
    - "warn"
    - argsIgnorePattern: "^_"
