version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Check Node.js version
          command: node -v
      - run:
          name: Update npm to latest version
          command: "sudo npm install -g npm@latest"
      - restore_cache:
          name: Restore node_modules from cache
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies if needed
          command: |
            if [ ! -d node_modules ]; then
              npm ci
            fi
      - save_cache:
          name: Cache node_modules
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Test
          command: npm test
      - run:
          name: Build
          command: npm run build
